### ISSUE TITLE
double click myapp.app : only support macOS 10.13 or Higher

### ISSUE THREAD

**Issue by humbass** [mimecorg/launchui-packager#1]
## pack command
`launchui-packager myapp 1.0.1 './dist/main.js' --out./packages`

## system version
`macOS Sierra  10.12.2`

**Comment by mischnic** [comment]
@mimecorg 

launchui was compiled for 10.13 (fix in https://github.com/mimecorg/launchui/pull/2):

```sh
$ for f in *; do echo ./$f; otool -l $f | grep -A2 "LC_VERSION_MIN_MACOSX"; done
./launchui
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.13
./libnode.57.dylib
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.7
./libui.A.dylib
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.8
```

**Comment by mimecorg** [comment]
Version 0.1.4 of launchui should now work on OS X 10.8+. Thank you both for reporting this issue and submitting the PR.
