### ISSUE TITLE
Different Node version

### ISSUE THREAD

**Issue by mischnic** [mimecorg/launchui-packager#2]
```
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/.../proton-launchui/node_modules/libui-node/nbind.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

```

I use Node 10 and launchui uses Node 8:
https://github.com/mimecorg/launchui/blob/140136272e1e7938465e90bee97e26ffd8625a1d/tools/download-deps.json#L3

Maybe launchui-packager should rebuild native modules to use Node 8 (electron packaging tools do this as well).

**Comment by mimecorg** [comment]
launchui comes which its own version of libui-node which is built against the same version of Node (8.11.1) which is shipped with launchui, so it looks like it's picking the wrong version of libui-node.

**Comment by mischnic** [comment]
> so it looks like it's picking the wrong version of libui-node.

Yes, if it works after I copied the bundle out of the build folder. But then:

Why aren't the (runtime) dependencies copied into the bundle (react & proton-native in this case), there's only: async-hooks, es6-shim, libui-node, nbind

**Comment by mimecorg** [comment]
libui-node and its dependencies are part of the launchui package so that there's no need to recompile anything. Other dependencies can be manually bundled with the application, at the moment launchui-packager doesn't do that automatically.

**Comment by mischnic** [comment]
> Other dependencies can be manually bundled with the application, at the moment launchui-packager doesn't do that automatically.

"Normal" dependencies can be bundled, but native modules needs to be copied as well. I've got it all working now after setting webpack up properly - also without moving the bundle.

**Comment by mimecorg** [comment]
I will definitely have to implement some solution for native modules at some point, but for now I want to focus on the remaining functionality of Vuido.
