### ISSUE TITLE
protect source code

### ISSUE THREAD

**Issue by wormen** [mimecorg/launchui-packager#4]
how to close the source code when building the executable file?

**Comment by mimecorg** [comment]
You can minify the source code while building the bundle to make it harder to read.

**Comment by wormen** [comment]
I'm interested in the implementation, as it is done in `electron`
`asar` archive is encrypting
your option, unfortunately does not fit

**Comment by mimecorg** [comment]
Electron asar doesn’t encrypt the script files, it just merges them.

**Comment by wormen** [comment]
not so long ago, it was really so
but now `asar` is encrypted by default

**Comment by wormen** [comment]
for the assembly of `electron` applications is used https://github.com/electron-userland/electron-builder
I did not go into the details of encryption

**Comment by mimecorg** [comment]
Yes, electron-builder provides code signing, but I couldn’t find any information about encryption. Also, if the scripts were encrypted, you would have to somehow procide the decryption key; either by including it in the package, which defeats the purpose of encryption, or by using a licensing server which provides the encryption key.

**Comment by wormen** [comment]
there is added a module for decryption, and the key itself is stitched somewhere in the code

**Comment by TheJaredWilcurt** [comment]
@wormen Electron does not support any form of source protection. NW.js however does via V8 snapshots.

* http://docs.nwjs.io/en/latest/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/

**Comment by wormen** [comment]
@TheJaredWilcurt 
I do not agree with you
I have 2 applications on `Electron `, where the sources are protected

**Comment by TheJaredWilcurt** [comment]
@wormen 

It isn't a matter of agreement, the best you can do with Electron is source obfuscation, not source protection. Electron explicitly states that they do not offer any form of source protection.

* https://github.com/electron/electron/issues/2570

**Note:** The first response from 2015 stating NW.js's source protection comes at a huger performance decrease is no longer true. There is no longer a performance cost incurred with using Source Protection in NW.js.

* * *

In Electron, you can minify/uglify the source code, and you and wrap it in an Asar (glorified zip file), but if someone is familiar with Electron, they can extract the source code directly with ease. And though it may be uglified, it is still all there and can be reconstructed. This is obfuscation, not protection.

Though it is theoretically possible to disassemble a V8 snapshot's bytecode, there are no known examples of anyone successfully reverse engineering a V8 snapshot.

* * *

I'm sorry to tell you but your 2 applications made with Electron are not secure.

**Comment by wormen** [comment]
@TheJaredWilcurt 
You are in the wrong place looking for the answer to the question
I have referred to above

in the `Electron` there is no such functional, it really is so

**Comment by TheJaredWilcurt** [comment]
@wormen I think you are confusing the concept of source code protection with code signing.

* **Source Code Protection:** Building your source JavaScript code to a native Binary, where there is no way to recover the original source code.
  * NW.js does this. Electron and LibUI-Node do not.
* **Code-Signing:** A digital signature that can be added to a package that proves it is an authentic release from the maker of the software, and not someone else pretending to be them.
  * You can do this with NW.js and Electron. I don't think anyone has created a simple way of doing this with LibUI-Node yet.
* **Hash Verification:** When the maker of the program includes a file hash (usually MD5 hashing) of the downloadable installer. This allows the user to check the file's hash after downloading to ensure that the file downloaded correctly and was not tampered with by third parties.
  * You can do this with literally any file.
