### ISSUE TITLE
Question about node_modules folder

### ISSUE THREAD

**Issue by Darkle** [mimecorg/launchui-packager#5]
Hi, when I run launchui-packager it doesn't seem to copy the files/folders from my node_modules directory - just wondering if I'm doing something wrong or if it's by design?

I'm running it with:
`launchui-packager auto-convert-talk-videos 0.0.1 app/appMain-compiled.js --out build --overwrite`

Cheers.

**Comment by mimecorg** [comment]
It's by design - you would typically bundle all modules into one large script, so there is no need to include node_modules. If there are any native dependencies which cannot be bundled, you can copy them using the dir and files options.

**Comment by Darkle** [comment]
Thanks.
